### ISSUE TITLE
1.9-0.0.1 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [MikeLydeamore/SimpleLabels#10]
Issue: simplelables-1.9-0.0.1 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/75664d0dfc7a24e7215d24dd5e403aaa

fml server latest:
https://gist.github.com/121cd3497bf594f6a9f0d026a72e28b2

**Comment by Amperthorpe** [comment]
I also have this same crash.

**Comment by tterrag1098** [comment]
Your forge is too new, things changed.

**Comment by blockbreaker1361** [comment]
I'm getting the same crash. Most new mods are requiring Forge 1833. Please update to accommodate these changes.

**Comment by tterrag1098** [comment]
As of the time of your comment, 1833 had been out for **_14 HOURS**_. Do you expect us to be your 24/7 modding slaves?

**Comment by blockbreaker1361** [comment]
Thanks for the RUDE comment. I wasn't being rude. I was just giving you info on what was happening with your mod.

**Comment by tterrag1098** [comment]
"Most new mods are requiring Forge 1833." is not helpful. It's also improbable considering the time scale. Just try to remember that we do this in our spare time for free, that's all.
