### ISSUE TITLE
Doesn't check NBT Data?

### ISSUE THREAD

**Issue by LezChap** [MikeLydeamore/SimpleLabels#12]
If the item in the DSU uses NBT data, the label doesn't check the item you insert via the label to make sure that NBT matches, thus creating a dupe-esque bug.  (Think having a DSU or Golden Bag of Holding with valuables in it, add it to the DSU, then adding empty DSUs or Bags via labels...the empty bags will copy the NBT data of the one in the DSU, duping the valuables).

Fix:  Check and match NBT on inserting items via labels.

**Comment by Ommina** [comment]
MC Version 1.10.2
SimpleLabels 0.0.2

[ Edit: _How To_ guide removed ]

**Comment by MikeLydeamore** [comment]
Fun fact: I actually fixed this almost 10 months ago here 7f049010377871f5137315f637c933682fb7b431
But then I unfixed it when trying to resolve a conflict and never noticed. Give me a few hours to get home again and I'll put the changes back in place.
