### ISSUE TITLE
Items not rendering (Yellorium, Extreme Reactor)

### ISSUE THREAD

**Issue by Protheus** [MikeLydeamore/SimpleLabels#16]
A QSU with Yellorium (Extreme Reactor) doesn't display the yellorium ingot in the label

Top left is the QSU with yellorium
![2017-01-06_19 41 25](https://cloud.githubusercontent.com/assets/1455178/21728776/3642906a-d448-11e6-8b42-b3c0070a66a8.png)

When a label is attached the ingot doesn't render
![2017-01-06_19 42 53](https://cloud.githubusercontent.com/assets/1455178/21728810/5fce2a02-d448-11e6-8fcc-e923182536da.png)

**Comment by tterrag1098** [comment]
You need to have more than a stack inside, I think. The storage is not reporting the stack in the output slot.

**Comment by Protheus** [comment]
Thank you... Will try it out when i have more ingots
