### ISSUE TITLE
Items still disappearing.

### ISSUE THREAD

**Issue by Apocryphai** [MikeLydeamore/SimpleLabels#18]
Using SimpleLabels 1.10.2-0.0.2 and I'm still finding that items disappear on a regular basis when I'm offline. I set up a VSU with a label on it and a cobblegen feeding it yesterday. When it hit ~14m cobble I moved it and placed it next to my ME system with a storage bus. All worked fine until this afternoon when I find that the VSU now only seems to have 2 stacks of cobble in it, having eating the other 14 million.

Let me know if you need more info or a mod list etc.

**Comment by Lunetouche** [comment]
Had the same thing happen to me last night, using the same version as part of the skyfactory 3 pack on curse launcher. Had a 24 VSUs labbeled and hooked into a refined storage system with external storage bus, no errors in server log, just a couple of thousand items suddenly vanishing.

Edit: The VSUs dont stack when broken, so i think something may be in their data, just not wanting to play

**Comment by jpeaglesandkatz** [comment]
Breaking the unit, you also lose all items. Makes it kind of useless IMHO.
