### ISSUE TITLE
Ghost Items

### ISSUE THREAD

**Issue by Mattabase** [MikeLydeamore/SimpleLabels#3]
https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/09/2015-09-26_10-08-41.mp4

When used on the quantum storage unit from 

http://www.curse.com/mc-mods/minecraft/235121-quantumstorage

**Comment by tterrag1098** [comment]
I see two bugs here, one obviously is the ghost items, there needs to be a `!isRemote` check here: https://github.com/MikeLydeamore/SimpleLabels/blob/master/src/main/java/com/insane/simplelabels/block/BlockLabel.java#L99-L103

Second is the way items are spawned, they are spawned at the corner of the block which makes them go in an odd direction. The problem area is here: https://github.com/MikeLydeamore/SimpleLabels/blob/master/src/main/java/com/insane/simplelabels/tile/TileLabel.java#L70

I would set the item to the position of the IDSU block + 0.5 on each axis. Then offset by the face it's placed against \* 0.5 (this would spawn it on the edge of the block). Finally, give it some motion away from that face of the block so it moves towards the player.
