### ISSUE TITLE
Early crash during client startup

### ISSUE THREAD

**Issue by LlubNek** [MikeLydeamore/SimpleLabels#6]
Here's the crash report:
http://pastebin.com/xeKGfg99

And here's the log:
http://pastebin.com/6sBZzzBF

The important bit is probably:

> [01:31:59] [Client thread/WARN] [FML]: Unable to parse dependency string required-after:Forge@[11.15.1.1724,),after:MineFactoryReloaded
> [01:31:59] [Client thread/WARN] [FML]: Zip file simplelabels-1.8.9-0.0.2.jar failed to read properly, it will be ignored
> net.minecraftforge.fml.common.LoaderException: Unable to parse dependency string required-after:Forge@[11.15.1.1724,),after:MineFactoryReloaded

**Comment by MikeLydeamore** [comment]
Fixed in d0ac8a07afd913793f38318241f1b536a55de2df v 0.03
